
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - sudo chmod +x ./gradlew
      - echo ./gradlew build
      - rm -r ./jinhueng-api-gateway/build/libs/jinheung-api-gateway-1.0.1-plain.jar
      - ./gradlew bootJar -p ./jinhueng-api-gateway
      - rm -r ./jinheung-eureka-server/build/libs/jinheung-eureka-server-1.0.1-plain.jar
      - ./gradlew bootJar -p ./jinheung-eureka-server
      - rm -r ./client-proxy/build/libs/client-proxy-1.0.1-plain.jar
      - ./gradlew bootJar -p ./client-proxy
  post_build:
    commands:
artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - scripts/**
  discard-paths: yes
  cache:
    paths:
      - '/root/.m2/**/*'