spring:
  rabbitmq:
    host: localhost
    username: admin
    password: admin
    port: 15672
  redis:
    port: 6379
    host: localhost
token:
  access-token-expired: 21600
timezone-plus-hour: 0


management.metrics.export.cloudwatch:
  enabled: false
