spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: http://localhost:8082
        predicates:
         - Path=/user
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AuthFilterFactory=
  redis:
    host: localhost
    port: 6379
server:
  port: 8081
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
