spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id:
        uri: http://localhost:8082
        predicates:
         - Path=/user
        filters:
          - TokenRelay=
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

server:
  port: 8081
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
token:
  access-token-secret: awey34634561235GWSDGVdsgvdsfhyfasdzehgysurhrt232t6347yetseryesrytasrgdasdrgvbasdfgbaedsfrghaewrgaewrghaerghaerha34qw67yy45
  refresh-token-expired: 1209600
  access-token-expired: 1209600