spring:
  application:
    name: user-resource-service
server:
  port: 8082
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://admin:admin123@localhost:8761/eureka/
