spring:
  application:
    name: jinheung-product
  redis:
    port: 6379
    host: localhost


server:
  port: 8083
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
services:
  product:
    url: http://localhost:8051
  payment:
    url: http://localhost:8052
