spring:
  application:
    name: shop-main
  datasource:
    url: jdbc:mysql://localhost:3306/jinheung_shop_main?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    #      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shop_main_orchestration
      #      password: 1234
      authentication-database: admin
      auto-index-creation: true
server:
  port: 8083
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/