spring:
  application:
    name: api-gateway
  redis:
    port: 6379
    host: localhost
server:
  port: 8083
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

token:
  access-token-secret: awey34634561235GWSDGVdsgvdsfhyfasdzehgysurhrt232t6347yetseryesrytasrgdasdrgvbasdfgbaedsfrghaewrgaewrghaerghaerha34qw67yy45
  refresh-token-expired: 1209600
  access-token-expired: 1209600