spring:
  application:
    name: jinheung-product
  redis:
    port: 6379
    host: localhost
  elasticsearch:
    rest:
      username: root
      password: 1234

server:
  port: 8083
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

token:
  access-token-secret: awey34634561235GWSDGVdsgvdsfhyfasdzehgysurhrt232t6347yetseryesrytasrgdasdrgvbasdfgbaedsfrghaewrgaewrghaerghaerha34qw67yy45
  refresh-token-expired: 1209600
  access-token-expired: 1209600